Melhorias nas instruções de instalação para o Linux Ubuntu.
adorilson/colaboradados.github.io pull request #3
Opened 2019-10-28 23:15 UTC by HortenciaArliane

### Melhorias nas instruções de instalação para o Linux Ubuntu.

### Este PR faz o seguinte:

[ ] Inclui uma nova base de dados
[ ] Inclui nova funcionalidade
[ ] Altera o layout
[ ] Formatação ou refactor de código
[ ] Resolve a issue#{id}
[x] Melhorias na documentação

### Descrição

Melhorei a sessão de instalação no Linux Ubuntu.

2019-10-28 23:53 UTC, adorilson requested changes
Obrigado pelo seu PR, @HortenciaArliane .

Fiz algumas solicitações de revisão.
Sugiro utlizar o README do pythonbrasil/wiki como referencia: https://github.com/pythonbrasil/wiki/blob/pelican/README.md

2019-10-28 23:53 UTC, adorilson commented on README.md
>  - [**GitBash**](https://git-scm.com/download/linux)
Sugiro:
1. remover o Jekyll, pois ele não é um prequisito em si para começar a colaborar com o projeto. Alem de será instalado mais adiante.
1. Substituir GitBash por Git. No Ubuntu, temos o terminal do sistema que faz as vezes do Gitbash no Windows. (a  URL pode deixar a mesma.)

2019-10-28 23:53 UTC, adorilson commented on README.md
> +
Creio que o mais correto seria atualizar a lista de *pacotes*.

2019-10-28 23:53 UTC, adorilson commented on README.md
> +    $ sudo apt-get update
Substitua, aqui e adiante, apt-get por apt. Mais moderno e mais simples.

2019-10-28 23:53 UTC, adorilson commented on README.md
> +
Também pode juntar as duas instruções em um único período. E aí os dois comandos ficam em um único bloco.  Nesse período, pode explicar  que está sendo feito "Instale as dependencias e em seguinda execute o servidor".

2019-10-28 23:53 UTC, adorilson commented on README.md
>  2. Vá até a pasta onde você clonou o repositório em seu computador.
Como? Cabe uma instrução de como ir para a pasta `cd`

2019-10-29 00:31 UTC, HortenciaArliane commented
Sugestões aceitas e executadas.

2019-10-29 00:36 UTC, adorilson requested changes
Excelente, @HortenciaArliane 

Só mais duas correções simples necessárias.

2019-10-29 00:36 UTC, adorilson commented on README.md
> +1. Abra o terminal do [**Ubuntu**](https://www.ubuntu.com/) e para atualizar a lista de p digite:
Palavra foi comida.

2019-10-29 00:36 UTC, adorilson commented on README.md
> +    ```
Como são dois comandos em sequencia, pode ficar no mesmo bloco. Só tirar esses apostrofos.

2019-10-29 01:58 UTC, HortenciaArliane commented
Corrigido...

2019-10-29 11:46 UTC, adorilson approved these changes
PR aprovado. Congrats.

2019-10-31 20:53 UTC, merged